import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Button from '@/Components/Button'
import ButtonApple from '@/Components/ButtonApple'
import Footer from '@/Components/Footer'
import Buttonacc from '@/Components/Buttonacc'
import ButtonSignIn from '@/Components/ButtonSignIn'


export default function Home() {
  return (
    <>
      <Head>
        <title>Melissa Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;700;800&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.logocontainer}><img width="300px" className={styles.Logo} src="X_logo_2023_(white).png" /></div>
          <div className={styles.allleftcontent}>
            <h1 className={styles.happening}>Happening now</h1>
            <h2 className={styles.join}>Join today.</h2>
            <div className={styles.formcontainer}>
              <Button className={styles.button}/>
              <ButtonApple className={styles.button}/>
              <div className={styles.linebreak}>
                <div className={styles.line1}></div>
                <div className={styles.line2}></div>
                <p className={styles.or} size="15px">or</p>
              </div>
              <Buttonacc className={styles.button}/>
              <p className={styles.cookies}>By signing up, you agree to the <span className={styles.bluecookies}>Terms of Service</span> and <span className={styles.bluecookies}>Privacy Policy</span>, including <span className={styles.bluecookies}>Cookie Use.</span></p>
              <p className={styles.already}>Already have an account?</p>
              <ButtonSignIn/>
            </div>
          </div>
        </div>
        <Footer/>
      </main>
    </>
  )
}
