import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Button from '@/Components/Button'
import ButtonApple from '@/Components/ButtonApple'
import Footer from '@/Components/Footer'
import Buttonacc from '@/Components/Buttonacc'
import ButtonSignIn from '@/Components/ButtonSignIn'
import Form from '@/Components/Form'



export default function Home() {
  return (
    <>
      <Head>
        <title>Melissa Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;700;800&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.logocontainer}><img width="300px" className={styles.Logo} src="X_logo_2023_(white).png" /></div>
          <div className={styles.allleftcontent}>
            <h1 className={styles.happening}>Happening now</h1>
            <h2 className={styles.join}>Join today.</h2>
            <div className={styles.formcontainer}>
              <Form/>
            </div>
          </div>
        </div>
        <Footer className={styles.footer}/>
      </main>
    </>
  )
}
